# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GetAdesaPurchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=20)),
                ('vehicle_id', models.IntegerField(blank=True)),
                ('vehicle_make', models.CharField(blank=True, max_length=20)),
                ('vin_sticker', models.CharField(blank=True, max_length=20)),
                ('auction_id', models.IntegerField(blank=True)),
                ('year', models.IntegerField(blank=True)),
                ('model_name', models.CharField(blank=True, max_length=20)),
                ('mileage', models.IntegerField(blank=True)),
                ('unit_of_measurement', models.CharField(blank=True, max_length=20)),
                ('exterior_color', models.CharField(blank=True, max_length=10)),
                ('seller_name', models.CharField(blank=True, max_length=20)),
                ('purchase_date', models.DateTimeField()),
                ('title_status', models.CharField(blank=True, max_length=20)),
                ('pdi_status', models.CharField(blank=True, max_length=20)),
                ('transport_status', models.CharField(blank=True, max_length=20)),
                ('location_name', models.CharField(blank=True, max_length=20)),
                ('buyer_rep_name', models.CharField(blank=True, max_length=20)),
                ('buyer_fee', models.CharField(blank=True, max_length=20)),
                ('buyer_ad_and_other_fees', models.CharField(blank=True, max_length=20)),
                ('fees_hst', models.CharField(blank=True, max_length=20)),
                ('taxable_purchase_price', models.CharField(blank=True, max_length=20)),
                ('total_hst', models.CharField(blank=True, max_length=20)),
                ('total_price', models.CharField(blank=True, max_length=20)),
                ('last_update_date_adesa', models.DateTimeField(blank=True)),
                ('last_update_date_gsm', models.DateTimeField(blank=True)),
                ('void_boolean', models.BooleanField(max_length=10)),
                ('payment_status', models.CharField(blank=True, max_length=10)),
                ('amount', models.CharField(blank=True, max_length=20)),
                ('purchase_price', models.CharField(blank=True, max_length=20)),
                ('purchase_hst', models.CharField(blank=True, max_length=20)),
                ('bill_of_sale', models.URLField(blank=True)),
                ('checked', models.CharField(blank=True, max_length=15)),
                ('recalls', models.TextField(blank=True)),
                ('manufacturer_date', models.CharField(blank=True, max_length=20)),
                ('gvwr', models.CharField(blank=True, max_length=20)),
                ('gross_axle_weight_front', models.CharField(blank=True, max_length=20)),
                ('gross_axle_weight_rear', models.CharField(blank=True, max_length=20)),
                ('tire_size', models.CharField(blank=True, max_length=20)),
                ('tire_pressure_front', models.CharField(blank=True, max_length=20)),
                ('tire_pressure_rear', models.CharField(blank=True, max_length=20)),
                ('rim_size', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
