# Generated by Django 2.1.3 on 2018-12-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='lane',
            field=models.CharField(default='Check Online', max_length=5),
        ),
    ]
