# Generated by Django 2.1.3 on 2018-11-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carfax',
            name='origin_country',
            field=models.CharField(default='Check Online', max_length=15),
        ),
    ]
