# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getadesapurchases',
            name='amount',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='auction_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='bill_of_sale',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='buyer_ad_and_other_fees',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='buyer_fee',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='buyer_rep_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='checked',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='exterior_color',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='fees_hst',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='gross_axle_weight_front',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='gross_axle_weight_rear',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='gvwr',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='last_update_date_adesa',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='last_update_date_gsm',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='location_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='manufacturer_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='mileage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='model_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='payment_status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='pdi_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='purchase_hst',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='purchase_price',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='recalls',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='rim_size',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='seller_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='taxable_purchase_price',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='tire_pressure_front',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='tire_pressure_rear',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='tire_size',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='title_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='total_hst',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='total_price',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='transport_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='unit_of_measurement',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='vehicle_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='vehicle_make',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='vin_sticker',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='void_boolean',
            field=models.NullBooleanField(max_length=10),
        ),
        migrations.AlterField(
            model_name='getadesapurchases',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
