# Generated by Django 2.1.3 on 2018-11-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_carfax_origin_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetRecalls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(default='Check Online', max_length=20)),
                ('vin', models.CharField(max_length=20)),
                ('recalls', models.TextField(default='Check online')),
            ],
        ),
    ]
