# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181018_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarFax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=20)),
                ('structural_damage', models.CharField(default='Check Online', max_length=100)),
                ('total_loss', models.CharField(default='Check Online', max_length=100)),
                ('accident', models.CharField(default='Check Online', max_length=100)),
                ('airbags', models.CharField(default='Check Online', max_length=100)),
                ('odometer', models.CharField(default='Check Online', max_length=100)),
                ('recalls', models.CharField(default='Check Online', max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
