# Generated by Django 2.1.3 on 2019-01-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181213_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='getadesarunlist',
            name='mileage',
            field=models.CharField(default='Check Online', max_length=20),
        ),
        migrations.AddField(
            model_name='getadesarunlist',
            name='trim',
            field=models.CharField(default='Check Online', max_length=60),
        ),
        migrations.AlterField(
            model_name='getadesarunlist',
            name='img_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='getadesarunlist',
            name='year',
            field=models.IntegerField(blank=True),
        ),
    ]
