# Generated by Django 2.1.3 on 2018-12-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_getadesarunlist_lane'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getadesarunlist',
            name='lane',
            field=models.CharField(default='Check Online', max_length=10),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='lane',
            field=models.CharField(default='Check Online', max_length=10),
        ),
    ]
