# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_carfax'),
    ]

    operations = [
        migrations.AddField(
            model_name='carfax',
            name='html',
            field=models.TextField(default='Check Online'),
        ),
    ]
