# Generated by Django 2.1.3 on 2018-12-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_getrecalls'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetAdesaRunList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=20)),
                ('img_url', models.URLField()),
                ('year', models.IntegerField()),
                ('make', models.CharField(default='Check Online', max_length=20)),
                ('model', models.CharField(default='Check Online', max_length=20)),
                ('grade', models.IntegerField(default='Check Online')),
                ('colour', models.CharField(default='Check Online', max_length=20)),
                ('MMR', models.TextField(default='Check Online', max_length=50)),
                ('MID', models.CharField(default='Check Online', max_length=20)),
                ('GSMR', models.TextField(default='Check Online', max_length=50)),
                ('transactions', models.CharField(default='Check Online', max_length=20)),
                ('run_date', models.CharField(default='Check Online', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=20)),
                ('img_url', models.URLField()),
                ('year', models.IntegerField()),
                ('make', models.CharField(default='Check Online', max_length=20)),
                ('model', models.CharField(default='Check Online', max_length=20)),
                ('grade', models.IntegerField(default='Check Online')),
                ('colour', models.CharField(default='Check Online', max_length=20)),
                ('MMR', models.TextField(default='Check Online', max_length=50)),
                ('MID', models.CharField(default='Check Online', max_length=20)),
                ('GSMR', models.TextField(default='Check Online', max_length=50)),
                ('transactions', models.CharField(default='Check Online', max_length=20)),
                ('run_date', models.CharField(default='Check Online', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
