# Generated by Django 2.1.3 on 2019-01-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190114_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getadesarunlist',
            name='GSMR',
            field=models.TextField(default='Check Online'),
        ),
        migrations.AlterField(
            model_name='getadesarunlist',
            name='MID',
            field=models.TextField(default='Check Online'),
        ),
        migrations.AlterField(
            model_name='getadesarunlist',
            name='MMR',
            field=models.TextField(default='Check Online'),
        ),
        migrations.AlterField(
            model_name='getadesarunlist',
            name='suggested_retail',
            field=models.TextField(default='Check Online'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='GSMR',
            field=models.TextField(default='Check Online'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='MID',
            field=models.TextField(default='Check Online'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='MMR',
            field=models.TextField(default='Check Online'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='transactions',
            field=models.TextField(default='Check Online'),
        ),
    ]
