# Generated by Django 2.1.3 on 2018-12-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_getadesarunlist_shoppinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='carfax',
            name='run_date',
            field=models.CharField(default='Check Online', max_length=20),
        ),
        migrations.AddField(
            model_name='getrecalls',
            name='run_date',
            field=models.CharField(default='Check Online', max_length=20),
        ),
    ]
