# Generated by Django 2.1.3 on 2019-04-12 20:43

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190409_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getadesarunlist',
            name='MMR',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), size=None),
        ),
        migrations.AlterField(
            model_name='getadesarunlist',
            name='check',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default='n/a'), size=None),
        ),
        migrations.AlterField(
            model_name='getadesarunlist',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='MMR',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), size=None),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='check',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default='n/a'), size=None),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
