# Generated by Django 2.1.3 on 2018-11-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_carfax_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getadesapurchases',
            name='purchase_date',
            field=models.DateTimeField(null=True),
        ),
    ]
