# Generated by Django 2.1.3 on 2019-04-17 22:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190412_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getadesarunlist',
            name='MMR',
            field=models.CharField(default='n/a', max_length=50),
        ),
        migrations.AlterField(
            model_name='getadesarunlist',
            name='check',
            field=models.CharField(default='n/a', max_length=50),
        ),
        migrations.AlterField(
            model_name='getadesarunlist',
            name='extra',
            field=models.CharField(default='n/a', max_length=50),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='MMR',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='check',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
