# Generated by Django 2.1.3 on 2019-01-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190117_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='getadesarunlist',
            name='human_valuation',
            field=models.TextField(default='{error: error}'),
        ),
        migrations.AddField(
            model_name='getadesarunlist',
            name='run_no',
            field=models.CharField(default='Check Online', max_length=20),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='human_valuation',
            field=models.TextField(default='{error: error}'),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='run_no',
            field=models.CharField(default='Check Online', max_length=20),
        ),
    ]
