# Generated by Django 2.1.3 on 2019-01-31 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190124_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='getadesarunlist',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='getadesarunlist',
            name='human_valuation',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='human_valuation',
            field=models.TextField(default=' '),
        ),
    ]
