# Generated by Django 2.1.3 on 2019-01-31 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190131_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='getadesarunlist',
            options={'ordering': ['-id']},
        ),
    ]
