# Generated by Django 2.1.3 on 2019-02-05 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190131_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='getadesarunlist',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'ordering': ['id']},
        ),
    ]
