# Generated by Django 2.1.3 on 2019-02-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190205_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getadesarunlist',
            name='human_valuation',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='human_valuation',
            field=models.TextField(default='0'),
        ),
    ]
