# Generated by Django 2.1.3 on 2019-04-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190207_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getadesarunlist',
            name='grade',
            field=models.CharField(default='Check Online', max_length=20),
        ),
    ]
