# Generated by Django 2.1.3 on 2019-02-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190214_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='year',
            field=models.IntegerField(blank=True),
        ),
    ]
