# Generated by Django 2.1.3 on 2019-02-15 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190215_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getadesarunlist',
            name='year',
        ),
    ]
