# Generated by Django 2.1.3 on 2019-04-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190408_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getadesarunlist',
            name='year',
            field=models.CharField(default='Check Online', max_length=20),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='year',
            field=models.CharField(default='Check Online', max_length=20),
        ),
    ]
