# Generated by Django 2.1.3 on 2019-04-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190408_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='getadesarunlist',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='getadesapurchases',
            name='adesa_id',
            field=models.CharField(default='n/a', max_length=20),
        ),
        migrations.AddField(
            model_name='getadesarunlist',
            name='adesa_id',
            field=models.CharField(default='n/a', max_length=20),
        ),
        migrations.AddField(
            model_name='getadesarunlist',
            name='human_valuation',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='getadesarunlist',
            name='mileage',
            field=models.CharField(default='Check Online', max_length=20),
        ),
        migrations.AddField(
            model_name='getadesarunlist',
            name='run_no',
            field=models.CharField(default='Check Online', max_length=20),
        ),
        migrations.AddField(
            model_name='getadesarunlist',
            name='suggested_retail',
            field=models.TextField(default='{error: error}'),
        ),
        migrations.AddField(
            model_name='getadesarunlist',
            name='trim',
            field=models.CharField(default='Check Online', max_length=60),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='adesa_id',
            field=models.CharField(default='n/a', max_length=20),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='human_valuation',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='mileage',
            field=models.CharField(default='Check Online', max_length=20),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='run_no',
            field=models.CharField(default='Check Online', max_length=20),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='suggested_retail',
            field=models.CharField(default='{error: error}', max_length=250),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='trim',
            field=models.CharField(default='Check Online', max_length=60),
        ),
        migrations.AlterField(
            model_name='carfax',
            name='html',
            field=models.TextField(blank=True, default='Check Online'),
        ),
        migrations.AlterField(
            model_name='carfax',
            name='origin_country',
            field=models.CharField(default='Check Online', max_length=250),
        ),
        migrations.AlterField(
            model_name='getadesarunlist',
            name='GSMR',
            field=models.TextField(default='{error: error}'),
        ),
        migrations.AlterField(
            model_name='getadesarunlist',
            name='MID',
            field=models.TextField(default='{error: error}'),
        ),
        migrations.AlterField(
            model_name='getadesarunlist',
            name='MMR',
            field=models.TextField(default='{error: error}'),
        ),
        migrations.AlterField(
            model_name='getadesarunlist',
            name='grade',
            field=models.CharField(default='Check Online', max_length=20),
        ),
        migrations.AlterField(
            model_name='getadesarunlist',
            name='img_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='getadesarunlist',
            name='transactions',
            field=models.CharField(default='{error: error}', max_length=250),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='GSMR',
            field=models.TextField(default='{error: error}'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='MID',
            field=models.TextField(default='{error: error}'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='MMR',
            field=models.TextField(default='{error: error}'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='transactions',
            field=models.TextField(default='{error: error}'),
        ),
    ]
