# Generated by Django 2.1.3 on 2019-02-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_getadesarunlist_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='year',
        ),
        migrations.AddField(
            model_name='getadesarunlist',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
