# Generated by Django 2.1.3 on 2019-02-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190215_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
