# Generated by Django 2.1.3 on 2019-02-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_shoppinglist_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getadesarunlist',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
